name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BotBackend
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: './BotBackend/package-lock.json'
    - run: npm ci
    - run: npm run test

  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BotFrontend
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: './BotFrontend/package-lock.json'
    - run: npm ci
    - run: npm run build
